/*
 * This file is generated by jOOQ.
 */
package dev.armadeus.discord.audio.database.tables.records;


import dev.armadeus.discord.audio.database.tables.Lavalink;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LavalinkRecord extends UpdatableRecordImpl<LavalinkRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lavalink.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lavalink.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.lavalink.uri</code>.
     */
    public void setUri(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lavalink.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lavalink.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lavalink.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Lavalink.LAVALINK.ID;
    }

    @Override
    public Field<String> field2() {
        return Lavalink.LAVALINK.URI;
    }

    @Override
    public Field<String> field3() {
        return Lavalink.LAVALINK.PASSWORD;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUri();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUri();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public LavalinkRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public LavalinkRecord value2(String value) {
        setUri(value);
        return this;
    }

    @Override
    public LavalinkRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public LavalinkRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LavalinkRecord
     */
    public LavalinkRecord() {
        super(Lavalink.LAVALINK);
    }

    /**
     * Create a detached, initialised LavalinkRecord
     */
    public LavalinkRecord(String id, String uri, String password) {
        super(Lavalink.LAVALINK);

        setId(id);
        setUri(uri);
        setPassword(password);
    }
}
