/*
 * This file is generated by jOOQ.
 */
package dev.armadeus.discord.audio.database;

import dev.armadeus.discord.audio.database.tables.Lavalink;
import dev.armadeus.discord.audio.database.tables.records.LavalinkRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LavalinkRecord> LAVALINK_NODES_PKEY = Internal.createUniqueKey(Lavalink.LAVALINK, DSL.name("lavalink_nodes_pkey"), new TableField[] { Lavalink.LAVALINK.ID }, true);
}
