/*
 * This file is generated by jOOQ.
 */
package dev.armadeus.bot.database.core;


import dev.armadeus.bot.database.core.tables.Instances;
import dev.armadeus.bot.database.core.tables.records.InstancesRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<InstancesRecord> INSTANCES_PKEY = Internal.createUniqueKey(Instances.INSTANCES, DSL.name("instances_pkey"), new TableField[] { Instances.INSTANCES.ID }, true);
}
