/*
 * This file is generated by jOOQ.
 */
package dev.armadeus.bot.database.core;


import dev.armadeus.bot.database.core.tables.Instances;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.instances</code>.
     */
    public static final Instances INSTANCES = Instances.INSTANCES;
}
