/*
 * This file is generated by jOOQ.
 */
package dev.armadeus.bot.database;


import dev.armadeus.bot.database.tables.Guilds;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;
}
