/*
 * This file is generated by jOOQ.
 */
package dev.armadeus.discord.audio.database;


import dev.armadeus.discord.audio.database.tables.Lavalink;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.lavalink</code>.
     */
    public static final Lavalink LAVALINK = Lavalink.LAVALINK;
}
