
#The default configuration for Arma-Core services
[arma-core]
	#The bot token used to connect to discord, available at
	#Your token can be found at https://discord.com/developers/applications/
	token = ""
	#A set of shards this instance will service
	#A empty list will assume all shards are hosted by this instance
	shards = []
	#The total number of shards hosted by all instances
	#Required to properly shard a bot
	#More information available at https://discord.com/developers/docs/topics/gateway#sharding
	shardsTotal = 1
	#A list of Snowflakes identified as the owner of this bot
	#Used to handle commands executable by owners
	ownerIds = [118255810613608451]
	#A list of Snowflakes identified as developers of this bot
	#Used to handle commands executable by developers
	developerIds = [135923847147945985]
	#A set of prefixes used by the bot when the GuildConfig has not set any
	defaultPrefixes = ["!"]

[database]
	#Should we enable and use database connections to save bot/guild data
	enabled = false
	#Username used to connect to the database
	username = "postgres"
	#Password used to connect to the database
	password = "password"
	uri = "jdbc:postgresql://localhost:5432/postgres"

